use crate::data::app_data::seed_instagram_storage;
use crate::tokens::storage::primitive::Store;
if Store::read("ig.me.name").is_none() { seed_instagram_storage(); }

col()
        id("instagram_tagged")
        css("min-h-screen bg-black text-white pb-20 max-w-lg mx-auto")

        row()
            css("sticky top-0 z-50 bg-black border-b border-gray-800 px-4 py-3 items-center gap-3")
            btn("←")
                var("ghost")
                css("text-xl text-white")
                nav("instagram")
            txt("Photos of You")
                css("text-lg font-semibold flex-1")
            btn("⋮")
                var("ghost")
                css("text-xl")

        row()
            css("px-4 py-3 gap-3 items-start bg-gray-900/50 border-b border-gray-800")
            txt("👤")
                css("text-2xl flex-shrink-0 mt-0.5")
            col()
                css("gap-0.5 flex-1")
                txt("Posts you're tagged in appear here")
                    css("text-sm text-gray-300")
                txt("You can remove tags or hide posts from your profile")
                    css("text-xs text-gray-500")

        grid(3)
            css("grid-cols-3 gap-0.5")
            block()
                css("aspect-square bg-gray-900 overflow-hidden relative cursor-pointer")
                acts(vec![store_set("ig.viewing.post_id", "p_bob_1"), navigate("instagram_post")])
                img_block("https://picsum.photos/600/600?random=10")
                    css("w-full h-full object-cover block")
                row()
                    css("absolute bottom-1.5 left-1.5 items-center gap-1 bg-black/60 rounded-full pr-2")
                    block()
                        css("w-5 h-5 rounded-full overflow-hidden border border-white/50")
                        img_block("https://i.pravatar.cc/150?u=bob")
                            css("w-full h-full object-cover")
                    txt("Bob")
                        css("text-white text-[10px] font-medium truncate max-w-[60px]")
            block()
                css("aspect-square bg-gray-900 overflow-hidden relative cursor-pointer")
                acts(vec![store_set("ig.viewing.post_id", "p_diana_1"), navigate("instagram_post")])
                img_block("https://picsum.photos/600/600?random=20")
                    css("w-full h-full object-cover block")
                row()
                    css("absolute bottom-1.5 left-1.5 items-center gap-1 bg-black/60 rounded-full pr-2")
                    block()
                        css("w-5 h-5 rounded-full overflow-hidden border border-white/50")
                        img_block("https://i.pravatar.cc/150?u=diana")
                            css("w-full h-full object-cover")
                    txt("Diana")
                        css("text-white text-[10px] font-medium truncate max-w-[60px]")
            block()
                css("aspect-square bg-gray-900 overflow-hidden relative cursor-pointer")
                acts(vec![store_set("ig.viewing.post_id", "p_charlie_1"), navigate("instagram_post")])
                img_block("https://picsum.photos/600/600?random=30")
                    css("w-full h-full object-cover block")
                row()
                    css("absolute bottom-1.5 left-1.5 items-center gap-1 bg-black/60 rounded-full pr-2")
                    block()
                        css("w-5 h-5 rounded-full overflow-hidden border border-white/50")
                        img_block("https://i.pravatar.cc/150?u=charlie")
                            css("w-full h-full object-cover")
                    txt("Charlie")
                        css("text-white text-[10px] font-medium truncate max-w-[60px]")

        row()
            css("fixed bottom-0 left-0 right-0 bg-black/95 backdrop-blur border-t border-gray-800 py-2 px-4 justify-around items-center z-50 max-w-lg mx-auto")
            btn("🏠")
                var("ghost")
                css("text-2xl opacity-60")
                nav("instagram_home")
            btn("🔍")
                var("ghost")
                css("text-2xl opacity-60")
                nav("instagram_explore")
            btn("➕")
                var("ghost")
                css("text-2xl opacity-60")
                nav("instagram_create")
            btn("🎬")
                var("ghost")
                css("text-2xl opacity-60")
                nav("instagram_reels")
            btn("♡")
                var("ghost")
                css("text-2xl opacity-60")
                nav("instagram_notifications")
            btn("👤")
                var("ghost")
                css("text-2xl")
                nav("instagram")
