use crate::tokens::builders::prelude::*;
use crate::tokens::node::IntoToken;
use crate::data::app_data::seed_products;

pub fn page_token() -> impl IntoToken {
    let products = seed_products();
    col()
        id("shop_page")
        css("min-h-screen bg-gray-50")
        row()
            css("sticky top-0 z-50 bg-white border-b px-4 py-3 items-center justify-between")
            txt("Shop")
                css("text-xl font-bold")
            row()
                css("gap-4")
                txt("🔍")
                    css("text-xl")
                txt("🛒")
                    css("text-xl")
        row()
            css("px-4 py-3 gap-2 overflow-x-auto scrollbar-none")
            .child(pill_chip("All"))
            .child(pill_chip("Home"))
            .child(pill_chip("Tech"))
            .child(pill_chip("Fashion"))
            .child(pill_chip("Beauty"))
        grid(2)
            css("gap-2 px-2 py-2 sm:gap-4 sm:px-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4")
            .children(products.iter().map(|p| {
                col()
                    .css("bg-white rounded-xl overflow-hidden shadow-sm")
                    .child(img_block(p.image_url.as_str())
                        .css("w-full aspect-square object-cover")
                    )
                    .child(col().css("p-3 gap-1")
                        .child(text(p.name.as_str()).css("text-sm font-medium line-clamp-2"))
                        .child(row().css("items-center gap-1")
                            .child(text("★").css("text-yellow-500 text-xs"))
                            .child(text(format!("{:.1}", p.rating)).css("text-xs text-gray-600"))
                            .child(text(format!("({})", p.reviews)).css("text-xs text-gray-400"))
                        )
                        .child(text(format!("${:.2}", p.price)).css("text-lg font-bold"))
                    )
            }))
        row()
            css("fixed bottom-0 left-0 right-0 bg-white border-t py-3 px-8 justify-between")
            txt("🏠")
                css("text-xl")
            txt("♡")
                css("text-xl")
            txt("🛒")
                css("text-xl text-blue-600")
            txt("👤")
                css("text-xl")
.end()
}

fn pill_chip(label: &str) -> impl IntoToken {
    block()
        css("px-4 py-1.5 bg-gray-900 text-white rounded-full text-sm whitespace-nowrap")
        txt(label)
            css("text-sm")
    .end()
}
